import Colors from '../../constants/Colors';

export const GeneralAppsData = [
  {
    app: true,
    appTitle: 'CAM',
    appIcon: 'documents',
    appColor: Colors.primaryColor,
    platform: 'both',
    isActive: true,
  },
  {
    app: true,
    appTitle: 'TARA',
    appIcon: 'documents',
    appColor: Colors.primaryColor,
    platform: 'both',
    isActive: true,
  },
  {
    app: true,
    appTitle: 'Ekspedisi Online',
    appIcon: 'car',
    appColor: Colors.secondaryColor,
    platform: 'both',
    isActive: true,
  },
  {
    app: true,
    appTitle: 'Sensory Online',
    appIcon: 'scan',
    appColor: Colors.primaryColor,
    platform: 'android',
    isActive: true,
  },
  {
    app: true,
    appTitle: 'Reservasi Mobil',
    appIcon: 'car',
    appColor: Colors.primaryColor,
    platform: 'both',
    isActive: false,
  },
  {
    app: true,
    appTitle: 'Chatbot',
    appIcon: 'chatbubble-ellipses',
    appColor: Colors.primaryColor,
    platform: 'both',
    isActive: false,
  },
  {
    app: true,
    appTitle: 'More',
    appIcon: 'apps',
    appColor: Colors.secondaryColor,
    platform: 'both',
    isActive: false,
  },
  {
    app: false,
    appTitle: 'More',
    appIcon: 'apps',
    appColor: Colors.secondaryColor,
    platform: 'both',
    isActive: false,
  },
];
